package com.github.mmonkey.Automator;

import org.spongepowered.api.block.BlockType;
import org.spongepowered.api.block.BlockTypes;
import org.spongepowered.api.item.ItemType;
import org.spongepowered.api.item.ItemTypes;

import java.util.HashMap;
import java.util.Map;

public class DefaultToolMapping {

    public static ItemType[] getBlockToolDefaults(BlockType block) {
        if (defaultMappings.containsKey(block)) {
            return defaultMappings.get(block);
        }
        return null;
    }

    private static Map<BlockType, ItemType[]> defaultMappings = new HashMap<BlockType, ItemType[]>();

    private static ItemType[] axes = {ItemTypes.WOODEN_AXE, ItemTypes.STONE_AXE, ItemTypes.IRON_AXE, ItemTypes.GOLDEN_AXE, ItemTypes.DIAMOND_AXE};
    private static ItemType[] pickaxes = {ItemTypes.WOODEN_PICKAXE, ItemTypes.STONE_PICKAXE, ItemTypes.IRON_PICKAXE, ItemTypes.GOLDEN_PICKAXE, ItemTypes.DIAMOND_PICKAXE};
    private static ItemType[] shears = {ItemTypes.SHEARS};
    private static ItemType[] shovels = {ItemTypes.WOODEN_SHOVEL, ItemTypes.STONE_SHOVEL, ItemTypes.IRON_SHOVEL, ItemTypes.GOLDEN_SHOVEL, ItemTypes.DIAMOND_SHOVEL};
    private static ItemType[] swords = {ItemTypes.WOODEN_SWORD, ItemTypes.STONE_SWORD, ItemTypes.IRON_SWORD, ItemTypes.GOLDEN_SWORD, ItemTypes.DIAMOND_SWORD};

    private static ItemType[] stonePickaxes = {ItemTypes.STONE_PICKAXE, ItemTypes.IRON_PICKAXE, ItemTypes.GOLDEN_PICKAXE, ItemTypes.DIAMOND_PICKAXE};
    private static ItemType[] ironPickaxes = {ItemTypes.IRON_PICKAXE, ItemTypes.GOLDEN_PICKAXE, ItemTypes.DIAMOND_PICKAXE};
    private static ItemType[] diamondPickaxes = {ItemTypes.DIAMOND_PICKAXE};

    public static void initialize() {
        loadBlockMappings();
    }

    private static void loadBlockMappings() {
        //defaultMappings.put(BlockTypes.AIR, );
        defaultMappings.put(BlockTypes.STONE, pickaxes);
        defaultMappings.put(BlockTypes.GRASS, shovels);
        defaultMappings.put(BlockTypes.DIRT, shovels);
        defaultMappings.put(BlockTypes.COBBLESTONE, pickaxes);
        defaultMappings.put(BlockTypes.PLANKS, axes);
        //defaultMappings.put(BlockTypes.SAPLING, );
        //defaultMappings.put(BlockTypes.BEDROCK, );
        //defaultMappings.put(BlockTypes.FLOWING_WATER, );
        //defaultMappings.put(BlockTypes.WATER, );
        //defaultMappings.put(BlockTypes.FLOWING_LAVA, );
        //defaultMappings.put(BlockTypes.LAVA, );
        defaultMappings.put(BlockTypes.SAND, shovels);
        defaultMappings.put(BlockTypes.GRAVEL, shovels);
        defaultMappings.put(BlockTypes.GOLD_ORE, ironPickaxes);
        defaultMappings.put(BlockTypes.IRON_ORE, stonePickaxes);
        defaultMappings.put(BlockTypes.COAL_ORE, pickaxes);
        defaultMappings.put(BlockTypes.LOG, axes);
        defaultMappings.put(BlockTypes.LOG2, axes);
        defaultMappings.put(BlockTypes.LEAVES, shears);
        defaultMappings.put(BlockTypes.LEAVES2, shears);
        //defaultMappings.put(BlockTypes.SPONGE, );
        //defaultMappings.put(BlockTypes.GLASS, );
        defaultMappings.put(BlockTypes.LAPIS_ORE, stonePickaxes);
        defaultMappings.put(BlockTypes.LAPIS_BLOCK, stonePickaxes);
        defaultMappings.put(BlockTypes.DISPENSER, pickaxes);
        defaultMappings.put(BlockTypes.SANDSTONE, pickaxes);
        defaultMappings.put(BlockTypes.NOTEBLOCK, axes);
        //defaultMappings.put(BlockTypes.BED, );
        defaultMappings.put(BlockTypes.GOLDEN_RAIL, pickaxes);
        defaultMappings.put(BlockTypes.DETECTOR_RAIL, pickaxes);
        //defaultMappings.put(BlockTypes.STICKY_PISTON, );
        defaultMappings.put(BlockTypes.WEB, shears);
        //defaultMappings.put(BlockTypes.TALLGRASS, );
        //defaultMappings.put(BlockTypes.DEADBUSH, );
        //defaultMappings.put(BlockTypes.PISTON, );
        //defaultMappings.put(BlockTypes.PISTON_HEAD, );
        defaultMappings.put(BlockTypes.WOOL, shears);
        //defaultMappings.put(BlockTypes.PISTON_EXTENSION, );
        //defaultMappings.put(BlockTypes.YELLOW_FLOWER, );
        //defaultMappings.put(BlockTypes.RED_FLOWER, );
        //defaultMappings.put(BlockTypes.BROWN_MUSHROOM, );
        //defaultMappings.put(BlockTypes.RED_MUSHROOM, );
        defaultMappings.put(BlockTypes.GOLD_BLOCK, ironPickaxes);
        defaultMappings.put(BlockTypes.IRON_BLOCK, stonePickaxes);
        defaultMappings.put(BlockTypes.DOUBLE_STONE_SLAB, pickaxes);
        defaultMappings.put(BlockTypes.STONE_SLAB, pickaxes);
        defaultMappings.put(BlockTypes.BRICK_BLOCK, pickaxes);
        //defaultMappings.put(BlockTypes.TNT, );
        defaultMappings.put(BlockTypes.BOOKSHELF, axes);
        defaultMappings.put(BlockTypes.MOSSY_COBBLESTONE, pickaxes);
        defaultMappings.put(BlockTypes.OBSIDIAN, diamondPickaxes);
        //defaultMappings.put(BlockTypes.TORCH, );
        //defaultMappings.put(BlockTypes.FIRE, );
        defaultMappings.put(BlockTypes.MOB_SPAWNER, pickaxes);
        defaultMappings.put(BlockTypes.OAK_STAIRS, axes);
        defaultMappings.put(BlockTypes.CHEST, axes);
        //defaultMappings.put(BlockTypes.REDSTONE_WIRE, );
        defaultMappings.put(BlockTypes.DIAMOND_ORE, ironPickaxes);
        defaultMappings.put(BlockTypes.DIAMOND_BLOCK, ironPickaxes);
        defaultMappings.put(BlockTypes.CRAFTING_TABLE, axes);
        //defaultMappings.put(BlockTypes.WHEAT, );
        defaultMappings.put(BlockTypes.FARMLAND, shovels);
        defaultMappings.put(BlockTypes.FURNACE, pickaxes);
        defaultMappings.put(BlockTypes.LIT_FURNACE, pickaxes);
        defaultMappings.put(BlockTypes.STANDING_SIGN, axes);
        defaultMappings.put(BlockTypes.WOODEN_DOOR, axes);
        defaultMappings.put(BlockTypes.SPRUCE_DOOR, axes);
        defaultMappings.put(BlockTypes.BIRCH_DOOR, axes);
        defaultMappings.put(BlockTypes.JUNGLE_DOOR, axes);
        defaultMappings.put(BlockTypes.ACACIA_DOOR, axes);
        defaultMappings.put(BlockTypes.DARK_OAK_DOOR, axes);
        defaultMappings.put(BlockTypes.LADDER, axes);
        defaultMappings.put(BlockTypes.RAIL, pickaxes);
        defaultMappings.put(BlockTypes.STONE_STAIRS, pickaxes);
        defaultMappings.put(BlockTypes.WALL_SIGN, axes);
        //defaultMappings.put(BlockTypes.LEVER, );
        defaultMappings.put(BlockTypes.STONE_PRESSURE_PLATE, pickaxes);
        defaultMappings.put(BlockTypes.IRON_DOOR, pickaxes);
        defaultMappings.put(BlockTypes.WOODEN_PRESSURE_PLATE, axes);
        defaultMappings.put(BlockTypes.REDSTONE_ORE, ironPickaxes);
        defaultMappings.put(BlockTypes.LIT_REDSTONE_ORE, ironPickaxes);
        //defaultMappings.put(BlockTypes.UNLIT_REDSTONE_TORCH, );
        //defaultMappings.put(BlockTypes.REDSTONE_TORCH, );
        defaultMappings.put(BlockTypes.STONE_BUTTON, pickaxes);
        defaultMappings.put(BlockTypes.SNOW_LAYER, shovels);
        //defaultMappings.put(BlockTypes.ICE, );
        defaultMappings.put(BlockTypes.SNOW, shovels);
        //defaultMappings.put(BlockTypes.CACTUS, );
        defaultMappings.put(BlockTypes.CLAY, shovels);
        //defaultMappings.put(BlockTypes.REEDS, );
        defaultMappings.put(BlockTypes.JUKEBOX, axes);
        defaultMappings.put(BlockTypes.FENCE, axes);
        defaultMappings.put(BlockTypes.SPRUCE_FENCE, axes);
        defaultMappings.put(BlockTypes.BIRCH_FENCE, axes);
        defaultMappings.put(BlockTypes.JUNGLE_FENCE, axes);
        defaultMappings.put(BlockTypes.DARK_OAK_FENCE, axes);
        defaultMappings.put(BlockTypes.ACACIA_FENCE, axes);
        defaultMappings.put(BlockTypes.PUMPKIN, axes);
        defaultMappings.put(BlockTypes.NETHERRACK, pickaxes);
        defaultMappings.put(BlockTypes.SOUL_SAND, shovels);
        //defaultMappings.put(BlockTypes.GLOWSTONE, );
        //defaultMappings.put(BlockTypes.PORTAL, );
        defaultMappings.put(BlockTypes.LIT_PUMPKIN, axes);
        //defaultMappings.put(BlockTypes.CAKE, );
        //defaultMappings.put(BlockTypes.UNPOWERED_REPEATER, );
        //defaultMappings.put(BlockTypes.POWERED_REPEATER, );
        defaultMappings.put(BlockTypes.TRAPDOOR, axes);
        defaultMappings.put(BlockTypes.MONSTER_EGG, pickaxes);
        defaultMappings.put(BlockTypes.STONEBRICK, pickaxes);
        defaultMappings.put(BlockTypes.BROWN_MUSHROOM_BLOCK, axes);
        defaultMappings.put(BlockTypes.RED_MUSHROOM_BLOCK, axes);
        defaultMappings.put(BlockTypes.IRON_BARS, pickaxes);
        //defaultMappings.put(BlockTypes.GLASS_PANE, );
        //defaultMappings.put(BlockTypes.MELON_BLOCK, );
        //defaultMappings.put(BlockTypes.PUMPKIN_STEM, );
        //defaultMappings.put(BlockTypes.MELON_STEM, );
        defaultMappings.put(BlockTypes.VINE, shears);
        defaultMappings.put(BlockTypes.FENCE_GATE, axes);
        defaultMappings.put(BlockTypes.SPRUCE_FENCE_GATE, axes);
        defaultMappings.put(BlockTypes.BIRCH_FENCE_GATE, axes);
        defaultMappings.put(BlockTypes.JUNGLE_FENCE_GATE, axes);
        defaultMappings.put(BlockTypes.DARK_OAK_FENCE_GATE, axes);
        defaultMappings.put(BlockTypes.ACACIA_FENCE_GATE, axes);
        defaultMappings.put(BlockTypes.BRICK_STAIRS, pickaxes);
        defaultMappings.put(BlockTypes.STONE_BRICK_STAIRS, pickaxes);
        defaultMappings.put(BlockTypes.MYCELIUM, shovels);
        //defaultMappings.put(BlockTypes.WATERLILY, );
        defaultMappings.put(BlockTypes.NETHER_BRICK, pickaxes);
        defaultMappings.put(BlockTypes.NETHER_BRICK_FENCE, pickaxes);
        defaultMappings.put(BlockTypes.NETHER_BRICK_STAIRS, pickaxes);
        //defaultMappings.put(BlockTypes.NETHER_WART, );
        defaultMappings.put(BlockTypes.ENCHANTING_TABLE, pickaxes);
        defaultMappings.put(BlockTypes.BREWING_STAND, pickaxes);
        defaultMappings.put(BlockTypes.CAULDRON, pickaxes);
        //defaultMappings.put(BlockTypes.END_PORTAL, );
        //defaultMappings.put(BlockTypes.END_PORTAL_FRAME, );
        defaultMappings.put(BlockTypes.END_STONE, pickaxes);
        //defaultMappings.put(BlockTypes.DRAGON_EGG, );
        //defaultMappings.put(BlockTypes.REDSTONE_LAMP, );
        //defaultMappings.put(BlockTypes.LIT_REDSTONE_LAMP, );
        defaultMappings.put(BlockTypes.DOUBLE_WOODEN_SLAB, axes);
        defaultMappings.put(BlockTypes.WOODEN_SLAB, axes);
        defaultMappings.put(BlockTypes.COCOA, axes);
        defaultMappings.put(BlockTypes.SANDSTONE_STAIRS, pickaxes);
        defaultMappings.put(BlockTypes.EMERALD_ORE, ironPickaxes);
        defaultMappings.put(BlockTypes.ENDER_CHEST, pickaxes);
        //defaultMappings.put(BlockTypes.TRIPWIRE_HOOK, );
        //defaultMappings.put(BlockTypes.TRIPWIRE, );
        defaultMappings.put(BlockTypes.EMERALD_BLOCK, ironPickaxes);
        defaultMappings.put(BlockTypes.SPRUCE_STAIRS, axes);
        defaultMappings.put(BlockTypes.BIRCH_STAIRS, axes);
        defaultMappings.put(BlockTypes.JUNGLE_STAIRS, axes);
        defaultMappings.put(BlockTypes.COMMAND_BLOCK, axes);
        //defaultMappings.put(BlockTypes.BEACON, );
        defaultMappings.put(BlockTypes.COBBLESTONE_WALL, pickaxes);
        //defaultMappings.put(BlockTypes.FLOWER_POT, );
        //defaultMappings.put(BlockTypes.CARROTS, );
        //defaultMappings.put(BlockTypes.POTATOES, );
        defaultMappings.put(BlockTypes.WOODEN_BUTTON, axes);
        //defaultMappings.put(BlockTypes.SKULL, );
        defaultMappings.put(BlockTypes.ANVIL, pickaxes);
        defaultMappings.put(BlockTypes.TRAPPED_CHEST, axes);
        defaultMappings.put(BlockTypes.LIGHT_WEIGHTED_PRESSURE_PLATE, pickaxes);
        defaultMappings.put(BlockTypes.HEAVY_WEIGHTED_PRESSURE_PLATE, pickaxes);
        //defaultMappings.put(BlockTypes.UNPOWERED_COMPARATOR, );
        //defaultMappings.put(BlockTypes.POWERED_COMPARATOR, );
        defaultMappings.put(BlockTypes.DAYLIGHT_DETECTOR, axes);
        defaultMappings.put(BlockTypes.DAYLIGHT_DETECTOR_INVERTED, axes);
        defaultMappings.put(BlockTypes.REDSTONE_BLOCK, pickaxes);
        defaultMappings.put(BlockTypes.QUARTZ_ORE, pickaxes);
        defaultMappings.put(BlockTypes.HOPPER, pickaxes);
        defaultMappings.put(BlockTypes.QUARTZ_BLOCK, pickaxes);
        defaultMappings.put(BlockTypes.QUARTZ_STAIRS, pickaxes);
        defaultMappings.put(BlockTypes.ACTIVATOR_RAIL, pickaxes);
        defaultMappings.put(BlockTypes.DROPPER, pickaxes);
        defaultMappings.put(BlockTypes.STAINED_HARDENED_CLAY, pickaxes);
        //defaultMappings.put(BlockTypes.BARRIER, );
        defaultMappings.put(BlockTypes.IRON_TRAPDOOR, pickaxes);
        //defaultMappings.put(BlockTypes.HAY_BLOCK, );
        //defaultMappings.put(BlockTypes.CARPET, );
        defaultMappings.put(BlockTypes.HARDENED_CLAY, pickaxes);
        defaultMappings.put(BlockTypes.COAL_BLOCK, pickaxes);
        //defaultMappings.put(BlockTypes.PACKED_ICE, );
        defaultMappings.put(BlockTypes.ACACIA_STAIRS, axes);
        defaultMappings.put(BlockTypes.DARK_OAK_STAIRS, axes);
        //defaultMappings.put(BlockTypes.SLIME, );
        //defaultMappings.put(BlockTypes.DOUBLE_PLANT, );
        //defaultMappings.put(BlockTypes.STAINED_GLASS, );
        //defaultMappings.put(BlockTypes.STAINED_GLASS_PANE, );
        defaultMappings.put(BlockTypes.PRISMARINE, pickaxes);
        //defaultMappings.put(BlockTypes.SEA_LANTERN, );
        defaultMappings.put(BlockTypes.STANDING_BANNER, axes);
        defaultMappings.put(BlockTypes.WALL_BANNER, axes);
        defaultMappings.put(BlockTypes.RED_SANDSTONE, pickaxes);
        defaultMappings.put(BlockTypes.RED_SANDSTONE_STAIRS, pickaxes);
        defaultMappings.put(BlockTypes.DOUBLE_STONE_SLAB2, pickaxes);
        defaultMappings.put(BlockTypes.STONE_SLAB2, pickaxes);
    }

}
